targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/features/home/data/models/m_banner.dart
        options:
          explicit_to_json: true
          include_if_null: false
